# Generated by Django 4.2.5 on 2023-10-02 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie_rating_platform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="likes",
                to="movie_rating_platform.movie",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
