# Generated by Django 4.2.5 on 2023-10-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_rating_platform", "0002_alter_like_target_alter_rating_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="avatar",
            field=models.ImageField(
                default="avatars/black.jpg", upload_to="avatars/"
            ),
        ),
    ]
