# Generated by Django 4.2.5 on 2023-10-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_rating_platform", "0003_visitor_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="poster_link",
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(
                blank=True,
                height_field=280,
                null=True,
                upload_to="posters/",
                width_field=200,
            ),
        ),
    ]
