# Generated by Django 4.2.5 on 2023-10-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_rating_platform", "0004_remove_movie_poster_link_movie_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
    ]
